ALTER TABLE rothschild.`Contacts`
  MODIFY COLUMN firstName VARCHAR(255) CHARACTER SET utf8mb4,
  MODIFY COLUMN lastName VARCHAR(255) CHARACTER SET utf8mb4,
  MODIFY COLUMN metadata TEXT CHARACTER SET utf8mb4;

ALTER TABLE rothschild.`Currencies`
  MODIFY COLUMN name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,
  MODIFY COLUMN symbol VARCHAR(16) CHARACTER SET utf8mb4 NOT NULL;

ALTER TABLE rothschild.`Issuances`
  MODIFY COLUMN balanceRule TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN redemptionRule TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN name TEXT CHARACTER SET utf8mb4 NOT NULL,
  MODIFY COLUMN metadata TEXT CHARACTER SET utf8mb4;

ALTER TABLE rothschild.`LightrailTransactionSteps`
  MODIFY COLUMN code VARCHAR(255) CHARACTER SET utf8mb4;

ALTER TABLE rothschild.`Programs`
  MODIFY COLUMN name TEXT CHARACTER SET utf8mb4 NOT NULL,
  MODIFY COLUMN generateCode TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN balanceRule TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN redemptionRule TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN metadata TEXT CHARACTER SET utf8mb4;

ALTER TABLE rothschild.`StripeTransactionSteps`
  MODIFY COLUMN charge MEDIUMTEXT CHARACTER SET utf8mb4 NOT NULL;

ALTER TABLE rothschild.`Transactions`
  MODIFY COLUMN lineItems MEDIUMTEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN paymentSources TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN tax TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN metadata TEXT CHARACTER SET utf8mb4;

ALTER TABLE rothschild.`Values`
  MODIFY COLUMN codeLastFour VARCHAR(255) CHARACTER SET utf8mb4,
  MODIFY COLUMN balanceRule TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN redemptionRule TEXT CHARACTER SET utf8mb4,
  MODIFY COLUMN metadata TEXT CHARACTER SET utf8mb4;
