export interface LightrailMessage {
    /**
     * Dot-separated namespace of the message type.
     * eg: `lightrail.transaction.created`
     *
     * Naming guideline:
     * - Start with `lightrail` unless the message was generated by another system and
     *   we're simply passing it along (eg `stripe`).
     * - The name of the service should *not* be in the message name as that's an
     *   implementation detail.
     * - Messages that describe things that happened in the system (ie events) should
     *   be past tense.
     * - When applicable use CRUDL language (created, updated, deleted).
     */
    type: string;

    /**
     * The service that generated the event.
     * eg: `rothschild`
     */
    service: string;

    /**
     * The Lightrail userId of the user that generated the event (if any).
     */
    userId?: string;

    /**
     * The ISO-8601 date of when the message was generated.
     */
    createdDate: string;

    /**
     * The message body.  The shape is entirely dependent upon the type of the message.
     * Breaking changes are a big deal and need to be coordinated.  Adding new properties
     * is not a breaking change.
     */
    payload: any;
}
