export interface LightrailEvent {
    /**
     * Dot-separated namespace of the event type.
     * eg: `lightrail.transaction.created`
     *
     * Naming guideline:
     * - Start with `lightrail` unless the event was generated by another system and
     *   we're simply passing it along (eg `stripe`).
     * - Events that are starting should be in the verb tense.
     * - Events that have completed should be in the past tense.
     * - When applicable use CRUDL language (created, updated, deleted).
     * - The name of the service should *not* be in the event name as that's an
     *   implementation detail.
     */
    type: string;

    /**
     * The service that generated the event.
     * eg: `rothschild`
     */
    service: string;

    /**
     * The Lightrail userId of the user that generated the event (if any).
     */
    userId?: string;

    /**
     * The ISO-8601 date of when the event was generated.
     */
    createdDate: string;

    /**
     * The event body.  The shape is entirely dependent upon the type of the event.
     * Breaking changes are a big deal and need to be coordinated.  Adding new properties
     * is not a breaking change.
     */
    payload: any;
}
